### ISSUE TITLE
"inf" creates invalid JSON

### ISSUE THREAD

**Issue by snappizz** [crucialfelix/supercolliderjs#27]
```
sclang.interpret("inf");
-> Uncaught SyntaxError: Unexpected token I in JSON at position 0
```

**Comment by crucialfelix** [comment]
I guess there is no legal way to represent those in JSON. They are valid JavaScript, but not valid JSON.

http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

It is because they are properties of window, not primitive types.  window.Infinity  - anybody could redefine that.

```js
JSON.parse('{"num": Infinity}')
VM1027:1 Uncaught SyntaxError: Unexpected token I in JSON at position 8
    at JSON.parse (<anonymous>)
    at <anonymous>:1:6
(anonymous) @ VM1026:1

// maybe just use a string for now
JSON.parse('{"num": "Infinity"}')
Object {num: "Infinity"}
```

I could convert the JSON.parse result to real Infinity objects

**Comment by snappizz** [comment]
My workaround for now is to preprocess the object by replacing infinities with the strings "Infinity" and "-Infinity", and in JS I can postprocess numeric values using the unary `+` operator.
