### ISSUE TITLE
How to connect together scsynth and sclang in the same nodejs app.

### ISSUE THREAD

**Issue by lorenzorivosecchi** [crucialfelix/supercolliderjs#72]
What is the simplest way to connect an interpreter and a server in the same nodejs application.
This should be the desired behavior:

### Setup
- boot scsynth
- boot sclang

### Runtime
When a user input some text:
- feed sclang with input
- dispatch result to scsynth
- (hear a sound)

#### Version
v1.0.0.beta.1

**Comment by crucialfelix** [comment]
In this case you are using sclang to play the sound, so I think you should keep it simple and start the server from sclang as normal:

```supercollider
Server.default.boot;
```

Try that first.

I could add some way to boot both and to get sclang to connect to the already running scsynth. This would have two advantages:
- It would boot faster: don't have to wait for sclang to come up before starting scsynth
- If your node/electron app shuts down then the scsynth process will be shut down correctly because it is a child process of the node process.

Something like this would work, but I haven't tested it yet:

```js

Promise.all([
  sc.server.boot(),
  sc.lang.boot()
]).then(async ([server, lang]) => {

  // figure out what the correct values here are:
  await lang.interpret(`Server.default = Server.remote(name, addr, options, clientID)`);
  // now you can run code as if the server and lang are already booted
})
```

**Comment by lorenzorivosecchi** [comment]
That's great, thanks !!
